% Set default general parameters for transfer test.
function test_params = setdefaulttransferparams(test_params)

% Create default parameters.
default_params = struct(...
    'verbosity',1,...
    'test_models',{{'standardmdp','linearmdp'}},...
    'test_metrics',{{'misprediction','policydist','featexp','value',...
        'reward','rewarddemean','rewardmomentmatch'}});

% Set parameters.
test_params = filldefaultparams(test_params,default_params);
