% Fill in default parameters for the MMPBoost algorithm.
function algorithm_params = learchdefaultparams(algorithm_params)

% Create default parameters.
default_params = struct(...
    'seed',0,...
    'iterations',150,...
    'all_features',1,...
    'true_features',0,...
    'depth',4,...
    'function','linear');

% Set parameters.
algorithm_params = filldefaultparams(algorithm_params,default_params);
