% Get list of models and metric to use for testing, including long-form
% names.
function [test_models,test_metrics,test_model_names,test_metric_names] = ...
    getmetrics()

test_models = {...
    'standardmdp',...
    'linearmdp'...
    };

test_model_names = {...
    'Standard MDP',...
    'Linear MDP',...
    };

test_metrics = {...
    'misprediction',...
    'policydist',...
    'featexp',...
    'value',...
    'featvar',...
    'reward',...
    'rewarddemean',...
    'rewardmomentmatch'...
    };

test_metric_names = {...
    'Misprediction Rate',...
    'Policy Difference',...
    'Feature Expectation Distance',...
    'Expected Value',...
    'True Feature Variance',...
    'Reward Distance',...
    'Mean-Matched Reward Distance',...
    'Moment-Matched Reward Distance',...
    };
