% Fill in default parameters for the MMPBoost algorithm.
function algorithm_params = mmpboostdefaultparams(algorithm_params)

% Create default parameters.
default_params = struct(...
    'seed',0,...
    'depth',4,...
    'iterations',10,...
    'feature_indices',[]);

% Set parameters.
algorithm_params = filldefaultparams(algorithm_params,default_params);
